recipes:
  - https://www.monsieur-cuisine.com/es/recetas/detalle/ajoblanco-1/
  - https://www.monsieur-cuisine.com/es/recetas/detalle/crema-de-calabacin/
  - https://www.monsieur-cuisine.com/es/recetas/detalle/crema-de-esparragos-con-panceta-crujiente/
  - https://www.monsieur-cuisine.com/es/recetas/detalle/curry-de-calabaza-y-patata-con-leche-de-coco/
  - https://www.monsieur-cuisine.com/es/recetas/detalle/gambas-agridulces/
  - https://www.monsieur-cuisine.com/es/recetas/detalle/risotto-de-setas-con-parmesano/
